src/pretalx/orga/urls.py
from django.conf.urls import include, url

from pretalx.event.models.event import SLUG_CHARS
from pretalx.orga.views import cards

from .views import (
    auth, cfp, dashboard, event, mails, organiser, person,
    plugins, review, schedule, speaker, submission,
)

app_name = 'orga'
urlpatterns = [
    url('^login/$', auth.LoginView.as_view(), name='login'),
    url('^logout/$', auth.logout_view, name='logout'),

    url('^$', dashboard.DashboardView.as_view(), name='dashboard'),
    url('^me$', event.UserSettings.as_view(), name='user.view'),
    url('^me/subuser$', person.SubuserView.as_view(), name='user.subuser'),
    url('^invitation/(?P<code>\w+)$', event.InvitationView.as_view(), name='invitation.view'),

    url('^organiser/new$', organiser.OrganiserDetail.as_view(), name='organiser.create'),
    url(f'^organiser/(?P<organiser>[{SLUG_CHARS}]+)/', include([
        url('^$', organiser.OrganiserDetail.as_view(), name='organiser.view'),
        url('^teams/$', organiser.TeamDetail.as_view(), name='organiser.teams'),
        url('^teams/new$', organiser.TeamDetail.as_view(), name='organiser.teams.create'),
        url('^teams/(?P<pk>[0-9]+)$', organiser.TeamDetail.as_view(), name='organiser.teams.view'),
        url('^teams/(?P<pk>[0-9]+)/delete$', organiser.TeamDelete.as_view(), name='organiser.teams.delete'),
        url('^teams/(?P<pk>[0-9]+)/delete/(?P<user_pk>[0-9]+)$', organiser.TeamDelete.as_view(), name='organiser.teams.delete_member'),
        url('^teams/(?P<pk>[0-9]+)/uninvite$', organiser.TeamUninvite.as_view(), name='organiser.teams.uninvite'),
    ])),

    url('^event/new/$', event.EventWizard.as_view(), name='event.create'),

    url(f'^event/(?P<event>[{SLUG_CHARS}]+)/', include([
        url('^$', dashboard.EventDashboardView.as_view(), name='event.dashboard'),
        url('^users$', person.UserList.as_view(), name='event.user_list'),

        url('^cfp/questions$', cfp.CfPQuestionList.as_view(), name='cfp.questions.view'),
        url('^cfp/questions/new$', cfp.CfPQuestionDetail.as_view(), name='cfp.questions.create'),
        url('^cfp/questions/remind$', cfp.CfPQuestionRemind.as_view(), name='cfp.questions.remind'),
        url('^cfp/questions/(?P<pk>[0-9]+)$', cfp.CfPQuestionDetail.as_view(), name='cfp.question.view'),
        url('^cfp/questions/(?P<pk>[0-9]+)/delete$', cfp.CfPQuestionDelete.as_view(), name='cfp.question.delete'),
        url('^cfp/questions/(?P<pk>[0-9]+)/edit$', cfp.CfPQuestionDetail.as_view(), name='cfp.question.edit'),
        url('^cfp/questions/(?P<pk>[0-9]+)/toggle$', cfp.CfPQuestionToggle.as_view(), name='cfp.question.toggle'),
        url('^cfp/text$', cfp.CfPTextDetail.as_view(), name='cfp.text.view'),
        url('^cfp/types$', cfp.SubmissionTypeList.as_view(), name='cfp.types.view'),
        url('^cfp/types/new$', cfp.SubmissionTypeDetail.as_view(), name='cfp.types.create'),
        url('^cfp/types/(?P<pk>[0-9]+)$', cfp.SubmissionTypeDetail.as_view(), name='cfp.types.view'),
        url('^cfp/types/(?P<pk>[0-9]+)/delete$', cfp.SubmissionTypeDelete.as_view(), name='cfp.type.delete'),
        url('^cfp/types/(?P<pk>[0-9]+)/default$', cfp.SubmissionTypeDefault.as_view(), name='cfp.type.default'),

        url('^mails/', include([
            url('^(?P<pk>[0-9]+)$', mails.MailDetail.as_view(), name='mails.outbox.mail.view'),
            url('^(?P<pk>[0-9]+)/copy$', mails.MailCopy.as_view(), name='mails.outbox.mail.copy'),
            url('^(?P<pk>[0-9]+)/delete$', mails.OutboxPurge.as_view(), name='mails.outbox.mail.delete'),
            url('^(?P<pk>[0-9]+)/send$', mails.OutboxSend.as_view(), name='mails.outbox.mail.send'),
            url('^templates$', mails.TemplateList.as_view(), name='mails.templates.list'),
            url('^templates/new$', mails.TemplateDetail.as_view(), name='mails.templates.create'),
            url('^templates/(?P<pk>[0-9]+)$', mails.TemplateDetail.as_view(), name='mails.templates.view'),
            url('^templates/(?P<pk>[0-9]+)/delete$', mails.TemplateDelete.as_view(), name='mails.templates.delete'),
            url('^send$', mails.SendMail.as_view(), name='mails.send'),
            url('^sent$', mails.SentMail.as_view(), name='mails.sent'),
            url('^outbox$', mails.OutboxList.as_view(), name='mails.outbox.list'),
            url('^outbox/send$', mails.OutboxSend.as_view(), name='mails.outbox.send'),
            url('^outbox/purge$', mails.OutboxPurge.as_view(), name='mails.outbox.purge'),
        ])),

        url('^submissions$', submission.SubmissionList.as_view(), name='submissions.list'),
        url('^submissions/new$', submission.SubmissionContent.as_view(), name='submissions.create'),
        url('^submissions/cards/$', cards.SubmissionCards.as_view(), name='submissions.cards'),
        url('^submissions/(?P<code>[\w-]+)/', include([
            url('^$', submission.SubmissionContent.as_view(), name='submissions.content.view'),
            url('^submit$', submission.SubmissionStateChange.as_view(), name='submissions.submit'),
            url('^accept$', submission.SubmissionStateChange.as_view(), name='submissions.accept'),
            url('^reject$', submission.SubmissionStateChange.as_view(), name='submissions.reject'),
            url('^confirm', submission.SubmissionStateChange.as_view(), name='submissions.confirm'),
            url('^withdraw$', submission.SubmissionStateChange.as_view(), name='submissions.withdraw'),
            url('^delete', submission.SubmissionStateChange.as_view(), name='submissions.delete'),
            url('^cancel', submission.SubmissionStateChange.as_view(), name='submissions.cancel'),
            url('^questions$', submission.SubmissionQuestions.as_view(), name='submissions.questions.view'),
            url('^questions/edit$', submission.SubmissionQuestions.as_view(), name='submissions.questions.edit'),
            url('^speakers$', submission.SubmissionSpeakers.as_view(), name='submissions.speakers.view'),
            url('^speakers/add$', submission.SubmissionSpeakersAdd.as_view(), name='submissions.speakers.add'),
            url('^speakers/delete$', submission.SubmissionSpeakersDelete.as_view(), name='submissions.speakers.delete'),
            url('^reviews$', review.ReviewSubmission.as_view(), name='submissions.reviews'),
            url('^reviews/delete$', review.ReviewSubmissionDelete.as_view(), name='submissions.reviews.submission.delete'),
            url('^feedback/$', submission.FeedbackList.as_view(), name='submissions.feedback.list'),
        ])),

        url('^speakers$', speaker.SpeakerList.as_view(), name='speakers.list'),
        url('^speakers/(?P<pk>[0-9]+)$', speaker.SpeakerDetail.as_view(), name='speakers.view'),
        url('^speakers/(?P<pk>[0-9]+)/toggle-arrived$', speaker.SpeakerToggleArrived.as_view(), name='speakers.arrived'),
        url('^info$', speaker.InformationList.as_view(), name='speakers.information.list'),
        url('^info/new$', speaker.InformationDetail.as_view(), name='speakers.information.create'),
        url('^info/(?P<pk>[0-9]+)$', speaker.InformationDetail.as_view(), name='speakers.information.view'),
        url('^info/(?P<pk>[0-9]+)/delete$', speaker.InformationDelete.as_view(), name='speakers.information.delete'),

        url('^reviews$', review.ReviewDashboard.as_view(), name='reviews.dashboard'),

        url('^settings$', event.EventDetail.as_view(), name='settings.event.view'),
        url('^settings/mail$', event.EventMailSettings.as_view(), name='settings.mail.view'),

        url('^settings/team$', organiser.Teams.as_view(), name='settings.team.view'),
        url('^settings/team/new$', organiser.TeamDetail.as_view(), name='settings.team.add'),
        url('^settings/team/(?P<pk>[0-9]+)$', organiser.TeamDetail.as_view(), name='settings.team.detail'),
        url('^settings/team/(?P<pk>[0-9]+)/delete$', organiser.TeamDelete.as_view(), name='settings.team.delete'),
        url('^settings/team/(?P<pk>[0-9]+)/delete/(?P<user_pk>[0-9]+)$', organiser.TeamDelete.as_view(), name='settings.team.delete_member'),
        url('^settings/team/(?P<pk>[0-9]+)/uninvite$', organiser.TeamUninvite.as_view(), name='settings.team.uninvite'),
        url('^settings/plugins$', plugins.EventPluginsView.as_view(), name='settings.plugins.select'),

        url('^schedule/$', schedule.ScheduleView.as_view(), name='schedule.main'),
        url('^schedule/import$', schedule.ScheduleImportView.as_view(), name='schedule.import'),
        url('^schedule/export$', schedule.ScheduleExportView.as_view(), name='schedule.export'),
        url('^schedule/export/trigger$', schedule.ScheduleExportTriggerView.as_view(), name='schedule.export.trigger'),
        url('^schedule/export/download$', schedule.ScheduleExportDownloadView.as_view(), name='schedule.export.download'),
        url('^schedule/release$', schedule.ScheduleReleaseView.as_view(), name='schedule.release'),
        url('^schedule/reset$', schedule.ScheduleResetView.as_view(), name='schedule.reset'),
        url('^schedule/toggle$', schedule.ScheduleToggleView.as_view(), name='schedule.toggle'),
        url('^schedule/rooms$', schedule.RoomList.as_view(), name='schedule.rooms.list'),
        url('^schedule/rooms/new$', schedule.RoomDetail.as_view(), name='schedule.rooms.create'),
        url('^schedule/rooms/(?P<pk>[0-9]+)$', schedule.RoomDetail.as_view(), name='schedule.rooms.view'),
        url('^schedule/rooms/(?P<pk>[0-9]+)/delete$', schedule.RoomDelete.as_view(), name='schedule.rooms.delete'),
        url('^schedule/api/rooms/$', schedule.RoomListApi.as_view(), name='schedule.api.rooms'),
        url('^schedule/api/talks/$', schedule.TalkList.as_view(), name='schedule.api.talks'),
        url('^schedule/api/talks/(?P<pk>[0-9]+)/$', schedule.TalkUpdate.as_view(), name='schedule.api.update'),
        url(
            '^schedule/api/availabilities/(?P<talkid>[0-9]+)/(?P<roomid>[0-9]+)/$',
            schedule.RoomTalkAvailabilities.as_view(), name='schedule.api.availabilities'
        ),

src/pretalx/urls.py
import importlib
from contextlib import suppress

from django.apps import apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

plugin_patterns = []
for app in apps.get_app_configs():
    if hasattr(app, 'PretalxPluginMeta'):
        if importlib.util.find_spec(app.name + '.urls'):
            urlmod = importlib.import_module(app.name + '.urls')
            single_plugin_patterns = []
            if hasattr(urlmod, 'urlpatterns'):
                single_plugin_patterns += urlmod.urlpatterns
            plugin_patterns.append(
                url(r'', include((single_plugin_patterns, app.label)))
            )

urlpatterns = [
    url(r'^orga/', include('pretalx.orga.urls', namespace='orga')),
    url(r'^api/', include('pretalx.api.urls', namespace='api')),
    url(r'', include('pretalx.agenda.urls', namespace='agenda')),
    url(r'', include('pretalx.cfp.urls', namespace='cfp')),
    url(r'', include((plugin_patterns, 'plugins'))),
]

if settings.DEBUG:
    with suppress(ImportError):
        import debug_toolbar
        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pretalx/submission/models/feedback.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from pretalx.common.mixins import LogMixin


class Feedback(LogMixin, models.Model):
    talk = models.ForeignKey(
        to='submission.Submission',
        related_name='feedback',
        on_delete=models.PROTECT,
        verbose_name=_('Talk'),
    )
    speaker = models.ForeignKey(
        to='person.User',
        related_name='feedback',
        null=True, blank=True,
        on_delete=models.PROTECT,
        verbose_name=_('Speaker'),
    )
    rating = models.IntegerField(
        null=True, blank=True,
        verbose_name=_('Rating'),
    )
    review = models.TextField(
        verbose_name=_('Review'),
        help_text=_('You can use markdown here.'),
    )

    def __str__(self):
        """Help when debugging."""
        return f'Feedback(event={self.talk.event.slug}, talk={self.talk.title}, rating={self.rating})'

src/pretalx/submission/models/review.py
from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from pretalx.common.urls import EventUrls


class Review(models.Model):
    submission = models.ForeignKey(
        to='submission.Submission',
        related_name='reviews',
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        to='person.User',
        related_name='reviews',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        verbose_name=_('What do you think?'),
        null=True, blank=True,
    )
    score = models.IntegerField(
        verbose_name=_('Score'),
        null=True, blank=True,
    )
    override_vote = models.NullBooleanField(
        default=None, null=True, blank=True,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Review(event={self.submission.event.slug}, submission={self.submission.title}, user={self.user.nick}, score={self.score})'

    @classmethod
    def find_missing_reviews(cls, event, user):
        from pretalx.submission.models import SubmissionStates

        return event.submissions.filter(state=SubmissionStates.SUBMITTED) \
            .exclude(reviews__user=user) \
            .exclude(speakers__in=[user]) \
            .annotate(review_count=models.Count('reviews')) \
            .order_by('review_count', '?')

    @cached_property
    def event(self):
        return self.submission.event

    @cached_property
    def display_score(self):
        if self.override_vote is True:
            return _('Positive override')
        if self.override_vote is False:
            return _('Negative override (Veto)')
        if self.score is None:
            return 'ø'
        return self.submission.event.settings.get(f'review_score_name_{self.score}') or str(self.score)

    class urls(EventUrls):
        base = '{self.submission.orga_urls.reviews}'
        delete = '{base}/{self.pk}/delete'

src/pretalx/cfp/forms/submissions.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from pretalx.mail.models import QueuedMail


class SubmissionInvitationForm(forms.Form):
    speaker = forms.EmailField(label=_('Speaker E-Mail'))
    subject = forms.CharField(label=_('Subject'))
    text = forms.CharField(widget=forms.Textarea(), label=_('Text'))

    def __init__(self, submission, speaker, *args, **kwargs):
        self.submission = submission
        initial = kwargs.get('initial', {})
        subject = _('{speaker} invites you to join their talk!').format(speaker=speaker.name or speaker.nick)
        initial['subject'] = f'[{submission.event.slug}] {subject}'
        initial['text'] = _('''Hi!

I'd like to invite you to be a speaker in my talk »{title}«
at {event}. Please follow this link to join:

  {url}

I'm looking forward to it!
{speaker}''').format(
            event=submission.event.name, title=submission.title,
            url=submission.urls.accept_invitation.full(),
            speaker=speaker.name or speaker.nick,
        )
        super().__init__(*args, **kwargs)

    def save(self):
        QueuedMail(
            event=self.submission.event,
            to=self.cleaned_data['speaker'],
            subject=self.cleaned_data['subject'],
            text=self.cleaned_data['text'],
        ).send()

src/pretalx/orga/forms/schedule.py
from django.forms import FileField, Form, ModelForm

from pretalx.schedule.models import Schedule


class ScheduleReleaseForm(ModelForm):

    class Meta:
        model = Schedule
        fields = ('version', )


class ScheduleImportForm(Form):
    upload = FileField()

    class Meta:
        fields = ('upload', )

src/pretalx/orga/forms/submission.py
from django import forms
from django.utils.translation import ugettext as _

from pretalx.common.mixins.forms import ReadOnlyFlag
from pretalx.submission.models import Submission, SubmissionType


class SubmissionForm(ReadOnlyFlag, forms.ModelForm):

    def __init__(self, event, **kwargs):
        super().__init__(**kwargs)
        self.fields['submission_type'].queryset = SubmissionType.objects.filter(event=event)

        if not self.instance.pk:
            self.fields['speaker'] = forms.CharField(
                help_text=_('Add the email or nickname of the speaker holding the talk. They will be invited to create an account.')
            )
        self.fields['abstract'].widget.attrs['rows'] = 2

    class Meta:
        model = Submission
        fields = [
            'title', 'submission_type', 'abstract', 'description',
            'notes', 'content_locale', 'do_not_record', 'duration',
            'image',
        ]

src/pretalx/orga/forms/widgets.py
from django.forms import RadioSelect


class HeaderSelect(RadioSelect):
    option_template_name = 'orga/widgets/header_option.html'

src/pretalx/submission/forms/resource.py
from django import forms

from pretalx.submission.models import Resource


class ResourceForm(forms.ModelForm):

    class Meta:
        model = Resource
        fields = [
            'resource', 'description',
        ]

src/pretalx/orga/templates/orga/submission/answer_list.html
{% extends "orga/submission/base.html" %}
{% load i18n %}

{% block submission_content %}
    {% for answer in answer_list %}
        <h5>
            {{ answer.question.question }}
            <small>({{ answer.question.get_variant_display }})</small>
        </h5>
        {% if answer.question.variant == 'file' %}
            {% if answer.answer_file %}
                <i class="fa fa-file-o"></i> <a href="{{ answer.answer_file.url }}">{{ answer.answer_file }}</a>
            {% endif %}
        {% else %}
            »{{ answer.answer }}«
        {% endif %}
    {% empty %}
        {% trans "No questions have been answered at the moment." %}
    {% endfor %}
{% endblock %}

src/pretalx/orga/templates/orga/submission/base.html
{% extends "orga/base.html" %}
{% load i18n %}
{% load rules %}

{% block content %}
{% if submission %}
{% has_perm 'submission.edit_submission' request.user submission as can_edit_submission %}
{% has_perm 'orga.view_reviews' request.user request.event as can_view_reviews %}
    <legend>
        <span>
            »{{ submission.title }}«
            {% if submission.speakers.exists %}
                by {{ submission.display_speaker_names }}
            {% endif %}
            {% include "orga/submission/state_dropdown.html" with submission=submission %}
        </span>
    </legend>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if "submissions.content" in url_name %}active{% endif %}"
          href="{{ submission.orga_urls.base }}"
        >
            {% trans "Content" %}
        </a>
      </li>
      <li class="nav-item">
          <a
            class="nav-link {% if "submissions.speakers" in url_name %}active{% endif %}"
            href="{{ submission.orga_urls.speakers }}"
          >
            {% trans "Speakers" %}
          </a>
      </li>
      {% if request.event.submission_questions.count %}
          <li class="nav-item">
              <a
                class="nav-link {% if "submissions.questions" in url_name %}active{% endif %}"
                href="{{ submission.orga_urls.questions }}"
              >
                {% trans "Questions" %}
              </a>
          </li>
      {% endif %}
      {% if submission.feedback.count %}
          <li class="nav-item">
              <a
                class="nav-link {% if "submissions.feedback" in url_name %}active{% endif %}"
                href="{{ submission.orga_urls.feedback }}"
              >
                {% trans "Feedback" %}
              </a>
          </li>
      {% endif %}
      {% if can_view_reviews %}
      <li class="nav-item">
          <a
            class="nav-link {% if "reviews" in url_name %}active{% endif %}"
            href="{{ submission.orga_urls.reviews }}"
          >
            {% trans "Reviews" %}
          </a>
      </li>
    {% endif %}
    </ul>
{% endif %}
{% block submission_content %}
{% endblock %}
{% endblock %}

src/pretalx/orga/templates/orga/submission/delete.html
{% extends "orga/submission/base.html" %}
{% load i18n %}
{% load url_replace %}

{% block submission_content %}
    {% trans "Do you really want to delete this submission?" %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group pull-right">
            <a class="btn btn-secondary" href="{% if request.GET.from == 'list' %}{{ request.event.orga_urls.submissions }}{% else %}{{ submission.orga_urls.base }}{% endif %}">
                {% trans "Back" %}
            </a>
            <button type="submit" class="btn btn-danger">
                {% trans "Yes, delete" %}
            </button>
        </div>
    </form>
{% endblock %}

src/pretalx/orga/templates/orga/submission/feedback_list.html
{% extends "orga/submission/base.html" %}
{% load i18n %}
{% load rich_text %}

{% block submission_content %}
    {% for entry in feedback %}
    <div class="card feedback-card">
        <div class="card-body">
            {{ entry.review|rich_text }}
        </div>
    </div>
    {% empty %}
        {% trans "There has been no feedback for this talk yet." %}
    {% endfor %}
{% endblock %}

src/pretalx/orga/templates/orga/submission/review.html
{% extends "orga/submission/base.html" %}
{% load bootstrap4 %}
{% load i18n %}
{% load rich_text %}

{% block submission_content %}
    <div class="alert alert-info">
        <span>
        {% if not read_only %}
            {{ request.event.settings.review_help_text|rich_text }}
            {% if not form.instance.pk %}
                {% blocktrans trimmed %}
                    You will be able to see other reviews once you have given yours.
                {% endblocktrans %}
            {% endif %}
        {% else %}
            {% blocktrans trimmed %}
                This submission can no longer be reviewed, as a decision regarding its
                role in this event has already been made, or the review deadline is over.
            {% endblocktrans %}
        {% endif %}
        {% if override_left %}
            {% blocktrans trimmed with count=override_left %}
                You have <strong>{{ count }}</strong> override votes left.
            {% endblocktrans %}
        {% endif %}
        </span>
    </div>

    {% if not form.instance.pk and not read_only %}
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="id_text">{% trans "Submission Type" %}</label>
            <div class="col-md-9">
                {{ submission.submission_type }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="id_text">{% trans "Abstract" %}</label>
            <div class="col-md-9">
                {{ submission.abstract|rich_text }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="id_text">{% trans "Description" %}</label>
            <div class="col-md-9">
                {{ submission.description|rich_text }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="id_text">{% trans "Notes for the organiser" %}</label>
            <div class="col-md-9">
                {{ submission.notes|rich_text }}
            </div>
        </div>
        {% bootstrap_field form.score layout='event' %}
        {% bootstrap_form qform layout='event' %}
        {% bootstrap_field form.text layout='event' %}
        <div class="submit-group"><span></span>
            <div>
                <button type="submit" class="btn btn-lg btn-info">{% trans "Save" %}</button>
                <button type="submit" class="btn btn-lg btn-success" name="show_next" value="1">{% trans "Save and next" %}</button>
            </div>
        </div>
    </form>
    {% endif %}

    {% if form.instance.pk or read_only %}
    <table class="table review-table table-hover table-responsive-md">
            <tr>
                <th>{% trans "Points" %}</th>
                {% for field in qform %}
                    <th>{{ field.label }}</th>
                {% endfor %}
                <th>{% trans "Review" %}</th>
                <th></th>
            </tr>
        <tbody>
            {% if form.instance.pk or not read_only %}
            <tr><form method="post">
                {% csrf_token %}
                <td>{% bootstrap_field form.score layout="inline" %}</td>
                {% for field in qform %}
                    <td>{% bootstrap_field field layout="inline" %}</td>
                {% endfor %}
                <td>{% bootstrap_field form.text layout="inline" %}</td>
                <td>
                    {% if not read_only %}
                        <button type="submit" class="btn btn-success">{% trans "Save" %}
                    {% else %}
                        {{ request.user.get_display_name }}
                    {% endif %}
                </td>
            </form></tr>
            {% endif %}
            {% for review in reviews %}
                {% if review != form.instance %}
                    <tr>
                        <td>{{ review.score }}</td>
                        {% for answer in review.answers %}
                            <td>
                                {{ answer.answer }}
                            </td>
                        {% endfor %}
                        <td>{{ review.text }}</td>
                        <td>{{ review.user }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

src/pretalx/orga/templates/orga/submission/speakers.html
{% extends "orga/submission/base.html" %}
{% load compress %}
{% load i18n %}
{% load rich_text %}
{% load rules %}
{% load staticfiles %}

{% block submission_content %}
    {% has_perm 'submission.edit_speaker_list' request.user submission as can_edit_speakers %}
    {% if can_edit_speakers %}<div class="alert">
        <form method="POST" action="{{ submission.orga_urls.new_speaker }}" class="form flex-row">
            <label>
                {% trans "Add a speaker – by nickname if registered, by email to send an invitation" %}:<br>
            </label>
            {% csrf_token %}
            <div class="input-group d-flex flex-row">
                <input type="text" name="nick" id="id_speaker" class="form-control" />
                <button type="submit" class="btn btn-sm btn-success float-right"><i class="fa fa-plus"></i></button>
            </div>
        </form>
    </div>{% endif %}

    {% for speaker in speakers %}
        <legend>
            <a href="{% url "orga:speakers.view" event=request.event.slug pk=speaker.id %}">
                {{ speaker.name }}
            </a>
        </legend>
        <p>
            <h5>{% trans "Biography" %}:</h5>
            {{ speaker.biography|rich_text|default:"-" }}
        </p>
        <p>
        {% if speaker.other_submissions %}
            <h5>{% trans "Other submissions by this speaker:" %}</h5>
            <ul>
                {% for submission in speaker.other_submissions %}
                <li>
                    <a href="{{ submission.orga_urls.base }}">{{ submission.title }}</a>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
        </p>
        {% if can_edit_speakers %}
        <div class="submit-group"><span></span>
            <a href="{{ submission.orga_urls.delete_speaker }}?nick={{ speaker.nick }}"
                class="btn btn-lg btn-danger">
                <i class="fa fa-trash"></i> {% trans "Remove" %}
            </a>
        </div>
        {% endif %}
    {% endfor %}


    <span id="vars" remoteUrl="{{ request.event.orga_urls.users }}?search=%QUERY"></span>
    {% compress js %}
    <script type="text/javascript" src="{% static "vendored/typeahead.bundle.min.js" %}"></script>
    <script type="text/javascript" src="{% static "orga/js/speakers.js" %}"></script>
    {% endcompress %}
{% endblock %}